name: bluetooth
description: A new Flutter project.
publish_to: 'none' 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.8
  yaml: 

  cupertino_icons: ^1.0.2
  phosphor_flutter: ^2.1.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  test: ^1.25.2


flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  remove_alpha_ios: true
  android: true
  ios: true
  image_path: "assets/myoty_launcher_icon1.jpg"